server {
    listen 80;
    server_name _; # On accepte toutes les requêtes (IP ou Domaine)
    root /var/www/html/www;
    index products.php;

    location / {
        try_files $uri $uri/ /products.php;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php-app-tp6:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
