server {
    listen 80;
    server_name localhost;
    # Redirige tout le trafic HTTP vers HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    # Certificats SSL générés au point 1
    ssl_certificate /etc/nginx/ssl/woodytoys.crt;
    ssl_certificate_key /etc/nginx/ssl/woodytoys.key;

    # Sécurité renforcée
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Lien vers le container PHP
    location ~ \.php$ {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
