server {
    listen 80;
    server_name www.l2-4.ephec-ti.be l2-4.ephec-ti.be;

    root /var/www/html/www;
    index products.php index.php index.html;

    location / {
        try_files $uri $uri/ /products.php;
    }

    location ~ \.php$ {
        include fastcgi_params;
        # ICI : On met le BON nom pour que Nginx trouve PHP
        fastcgi_pass php-app-tp6:9000; 
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html/www$fastcgi_script_name;
    }
}
