



options {
    directory "/var/cache/bind";
    version "not currently available";
    allow-query { any; };
    allow-query-cache { none; };
    recursion no;
    dnssec-validation auto;
};

zone "l2-4.ephec-ti.be" {
    type master;
    file "/var/cache/bind/db.l2-4.ephec-ti.be";
    allow-transfer { none; };
    inline-signing yes;
    auto-dnssec maintain;
};
