limit_req_zone $binary_remote_addr zone=mylimit:10m rate=1r/m;

server {
    listen 80;

    limit_req zone=mylimit;
    limit_req_status 429;

    location /api/products {
        proxy_pass http://api-toys:5000;
    }

    location /api/misc/heavy {
        proxy_pass http://api-heavy:5000;
    }

    location / {
        proxy_pass http://front:80;
    }
}
