server {
  listen 80; # <--- CHANGE ÇA (Mets 80 à la place de 8080)

  location /api/products {
    proxy_pass http://api-toys:5000;
  }

  location /api/misc/heavy {
    proxy_pass http://api-heavy:5000;
  }

  location /api/orders {
    proxy_pass http://api-auth:5000;
  }

  location / {
    proxy_pass http://front:80;
    limit_rate 300k;
  }
}
