server {
    listen 80;
    server_name www.l2-4.ephec-ti.be l2-4.ephec-ti.be;

    # Page PHP produits de l'ancien TP
    location = /products.php {
        proxy_pass http://172.27.0.3/products.php;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 5s;
        proxy_read_timeout 15s;
    }

    # Ancienne route heavy : compatibilité
    location = /api/heavy {
        proxy_pass http://woodystack_api-heavy:5000/api/misc/heavy;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # TP9 : Service lourd
    location = /api/misc/heavy {
        proxy_pass http://woodystack_api-heavy:5000/api/misc/heavy;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # API Produits Woody
    location /api/products {
        proxy_pass http://woodystack_api-toys:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Backend général Woody
    location /api/ {
        proxy_pass http://woodystack_api-auth:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Site Woody principal
    location / {
        proxy_pass http://woodystack_front:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
