options {
    directory "/var/cache/bind";
    allow-query { any; };
    recursion no;
    listen-on { any; };
};

zone "l2-4.ephec-ti.be" {
    type master;
    file "/etc/bind/zones/db.l2-4.ephec-ti.be";
};
