services:
  nginx:
    build: ./nginx
    container_name: nginx-tp6
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./html/:/var/www/html/
    networks:
      - frontend
    depends_on:
      - php

  php:
    build: ./php
    container_name: php-tp6
    volumes:
      - ./html/:/var/www/html/
    env_file:
      - db.env
    networks:
      - frontend

  mariadb:
    image: mariadb:11.1
    container_name: mariadb-tp6
    env_file:
      - db/root.env
      - db.env
    volumes:
      - ./db/sql/:/docker-entrypoint-initdb.d/
      - ./mariadb/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

networks:
  frontend:
    name: tp6_fresh_frontend
  backend:
    name: tp6_fresh_backend

volumes:
  mariadb_data:
