services:
  nginx:
    build: ./nginx
    container_name: nginx-tp6
    # Let's Encrypt a besoin du port 80 pour valider que tu es le proprio du domaine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./nginx/letsencrypt:/etc/letsencrypt # Stockage persistant des certificats
    networks:
      - frontend
    depends_on:
      - php

  php:
    build: ./php
    container_name: php-tp6
    volumes:
      - ./html:/var/www/html
    networks:
      - frontend

  mariadb:
    image: mariadb:11.1
    container_name: mariadb-tp6
    env_file:
      - db.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - frontend

networks:
  frontend:
    external: true # Utilise ton réseau existant ou retire 'external' si tu veux qu'il le crée

volumes:
  mariadb_data:
