    events {}
     http {
          log_format log_per_virtualhost '[$host] $remote_addr [$time_local] $status "$request" $body_bytes_sent';
          access_log /dev/stdout log_per_virtualhost;

     # Premier site (www)
     server {
     listen 80;
     server_name www.l2-4.ephec-ti.be;
     index index.html;
     root /var/www/html/www/;
     }

     # Deuxième site (blog)
     server {
     listen 80;
     server_name blog.l2-4.ephec-ti.be; index index.html;
     root /var/www/html/blog/;
     }
}
