events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # ---- AJOUT TP5 : Format de logs personnalisé ----
    log_format log_per_virtualhost '[$host] $remote_addr [$time_local]  $status "$request" $body_bytes_sent';
    access_log /dev/stdout log_per_virtualhost;
    # -------------------------------------------------

    include       /etc/nginx/conf.d/*.conf;
    sendfile        on;
    keepalive_timeout  65;
}
