events {}
http {
    include /etc/nginx/mime.types;
    server {
        listen 80;
        server_name www.l2-4.ephec-ti.be;
        root /var/www/html/www;
        index index.php index.html;
        location ~* \.php$ {
            fastcgi_pass php:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
    server {
        listen 80;
        server_name blog.l2-4.ephec-ti.be;
        root /var/www/html/blog;
        index index.html;
    }
}
