# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/www.l2-4.ephec-ti.be
cert = /etc/letsencrypt/live/www.l2-4.ephec-ti.be/cert.pem
privkey = /etc/letsencrypt/live/www.l2-4.ephec-ti.be/privkey.pem
chain = /etc/letsencrypt/live/www.l2-4.ephec-ti.be/chain.pem
fullchain = /etc/letsencrypt/live/www.l2-4.ephec-ti.be/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 7e6a0b60c4afe1d50dfecbceb2febadc
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
