options {
    directory "/tmp";
    recursion no;
    allow-query { any; };
    allow-query-cache { none; };
    listen-on { any; };
    listen-on-v6 { any; };
};

zone "l2-4.ephec-ti.be" {
    type master;
    file "/etc/bind/db.l2-4.ephec-ti.be";
    allow-transfer { none; };
};
